language: python
python:
  - 2.6
  - 2.7
  - 3.3
install: "pip install Django==$DJANGO_VERSION --use-mirrors"
script: loginas/tests/manage.py test --verbosity=2 tests
env:
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.5.11
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1

matrix:
  exclude:
   - python: 3.3
     env: DJANGO_VERSION=1.4.16
   - python: 2.6
     env: DJANGO_VERSION=1.7.1
